models:
  violence: "./models/violence.pt"
  license_plate: "./models/license_plate.pt"
  rubbish: "./models/garbage.pt"
  bicylce: "./models/yolo11n.pt"
  pets: "./models/yolo11n.pt"
  vehicle: "./models/yolo11n.pt"
  person: "./models/yolo11n.pt"

confidence:
  violence: 0.85
  license_plate: 0.6
  rubbish: 0.85
  bicylce: 0.6
  pets: 0.6
  vehicle: 0.6
  person: 0.6

classes:
  bicycle: [1]
  pets: [15,16]
  vehicle: [2,3,5,7]
  person: [0]

robot:
  rtsp://localhost:8554/stream: "local test"
  rtsp://18.167.218.143:10554/34020000001320118007_34020000001320118007: "Genting"

camera:
  rtsp://localhost:8554/stream: "camera test"
  rtsp://18.167.218.143:10554/34020000001320118007_34020000001320118007: "alert camera"

# API endpoint settings
api:
  post_endpoint: "http://152.136.145.174:18000/aiAlarm/save"
  # post_endpoint: "http://post-server:8080/api/detections"
  timeout: 10


